# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(default=1)),
                ('memoria', models.IntegerField(default=4)),
                ('disco', models.IntegerField(default=250)),
                ('so', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
                ('provedores', models.CharField(max_length=150)),
                ('release', models.DateTimeField(verbose_name='lançamento')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ['preco'],
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
